version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: car-app-postgres
    environment:
      POSTGRES_DB: car-app
      POSTGRES_USER: car_user
      POSTGRES_PASSWORD: car_password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - car-app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: car-app-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@car-app.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8082:80"
    depends_on:
      - postgres
    networks:
      - car-app-network

volumes:
  postgres_data:

networks:
  car-app-network:
    driver: bridge
