import type { Metadata } from "next";
import { Header } from "./components/Header.tsx";

import "./globals.css";

export const metadata: Metadata = {
  title: "公用車管理アプリ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
